# Generated by Django 6.0.3 on 2026-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Notes/')),
            ],
        ),
    ]
