# Generated by Django 6.0.3 on 2026-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='Resources/')),
            ],
        ),
    ]
