# Generated by Django 5.2.7 on 2026-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_notes_file_alter_paper_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
