# Generated by Django 5.2.7 on 2026-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_resources_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='link',
        ),
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
